added logging and error handling to cluster_up script

diff --git a/roles/local-env/templates/cluster_up.sh.j2 b/roles/local-env/templates/cluster_up.sh.j2
--- a/roles/local-env/templates/cluster_up.sh.j2
+++ b/roles/local-env/templates/cluster_up.sh.j2
@@ -2,6 +2,7 @@
 
 CURRENT_DIRECTORY="{{ playbook_dir }}"
 CLUSTER_DIRECTORY="$CURRENT_DIRECTORY/replicas-cluster-{{ cluster.domain }}"
+LOG=/tmp/$(date +"%s")
 
 cat << "EOF"
 
@@ -21,7 +22,11 @@ echo "Starting cluster setup from scratch."
 sleep 1
 echo "STEP 1 - Deploying all infrastructure."
 sleep 3
-ansible-playbook $CURRENT_DIRECTORY/play_complete_cluster.yml --ask-vault-pass
+ansible-playbook $CURRENT_DIRECTORY/play_complete_cluster.yml --ask-vault-pass | tee $LOG
+if grep -q failed=[^0] "$log"; then
+  exit 1
+  echo "Execution of playbook failed."
+fi
 
 echo "##########"
 sleep 1
@@ -42,4 +47,8 @@ cp -r $CLUSTER_DIRECTORY/group_vars $CLUSTER_DIRECTORY/kubespray-run/inventory/m
 
 # Start the playbook
 cd "$CLUSTER_DIRECTORY/kubespray-run"
-ansible-playbook -i inventory/mycluster/inventory.ini --become --become-user=root cluster.yml
+ansible-playbook -i inventory/mycluster/inventory.ini --become --become-user=root cluster.yml | tee $LOG
+if grep -q failed=[^0] "$log"; then
+  exit 1
+  echo "Execution of playbook failed."
+fi
